#!/bin/sh

echo "This test script will run only on limited environment: Because test movies are too huge to put repository"

echo "---- Test 1 ----"
./a.out cat2.avi cat2.mpg

echo "---- Test 2 ----"
./a.out ~/Videos/utlug/4th/editted-1.avi cat2.mpg

