#!/bin/sh


date
echo "---- Test 1 ----"
./bin/yasy cat2.avi cat2.ogg

echo "---- Test 2 ----"
echo "This test2 script will run only on limited environment: Because test movies are too huge to put repository"
#./bin/yasy ~/Videos/utlug/4th/out.corn.avi cat2.avi
./bin/yasy ~/Videos/utlug/4th/editted-5.avi cat2.mp4
date

